### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by lopahn2** [lopahn2/nodeJS_Study#12]

**Comment by lopahn2** [comment]
# margin: auto auto;

“If “margin-top” or “margin-bottom” is “auto”, their used value is 0″

"margin-top과 margin-bottom이 auto이면 실제 값은 0이다."

block요소(div)들을 정렬할 때에는 아래 3번이 권장

---

3. flexbox

flexbox로 설정된 요소는

자식 요소들을 쉽게 정렬할 수 있습니다.

수평, 수직정렬 모두 가능합니다.

hooolly shiit man

**Comment by lopahn2** [comment]
# vw와 %로 전체화면을 커버하는 div를 설정할 수 없는 이유
https://codingbroker.tistory.com/56

---

1. %는 부모 요소 길이의 몇%를 차지할 것인지 나타내기 때문에 먼저는 부모 요소의 길이가 설정되어 있어야 한다.
2. vw, vh는 뷰포트의 길이에 영향을 받는다. (뷰포트란 해당 웹페이지를 실행하고 있는 기기(노트북, 스마트폰 등)의 화면크기를 말한다.)
3. 자세히 보시면 화면 전체를 차지하지 않고 끝부분에 여백이 있다. 100% 혹은 100vw, 100vh로 적용했는데 마치 100을 넘어간듯이 스크롤까지 생겨버렸다. 이유는 HTML 태그의 기본 margin 때문!! 없애주자.

**Comment by lopahn2** [comment]
# 배경이미지만 투명하게 하기
```css
body:after {
    background-image: url("../login-gif.gif");
    top:0;
    left:0;
    position:absolute;
    opacity:0.5!important;
    filter:alpha(opacity=50);
    z-index:-1;
    content:"";
    width:100%;
    height:100%;
background-repeat : repeat;
}
```
