### ISSUE TITLE
CSS/ 배경이미지만 투명하게 하기

### ISSUE THREAD

**Issue by lopahn2** [lopahn2/nodeJS_Study#8]
```css
body:after {
    background-image: url("../login-gif.gif");
    top:0;
    left:0;
    position:absolute;
    opacity:0.5!important;
    filter:alpha(opacity=50);
    z-index:-1;
    content:"";
    width:100%;
    height:100%;
	background-repeat : repeat;
}
```

wow!
